
def staff_menu():
    staff_bar = input("SEARCH:")
    if staff_bar == "cmds":
        print("―――――――――――――")
        print("[*] cmds")
        print("[*] credits")
        print("[*] rules")
        print("[*] info")
        print("[*] nextUPD")
        print("[*] warn_reason")
        print("[*] ban_reason")
        print("[*] exit")
        print("―――――――――――――")
        staff_menu()
    elif staff_bar == "credits":
        print("―――――――――――――")
        print("[!] Credits")
        print()
        print("[*] CREATOR: alexis20114")
        staff_menu()
    elif staff_bar == "rules":
        print("―――――――――――――")
        print("📜 [!] Rules")
        print("⚠️ Respect Everyone – No bullying, discrimination, or toxic behavior.")
        print("🚫 No Spamming – Keep the chat clean and meaningful.")
        print("🛡️ Follow Admin Instructions – Mods' decisions are final.")
        print("📢 Keep It On Topic – Stay relevant to the chat or discussion.")
        print("🔞 No NSFW Content – Keep it appropriate for all members.")
        print("🔗 No Unapproved Links – Sharing harmful or unauthorized links is not allowed.")
        print("💬 Use Proper Channels – Follow the correct categories when posting.")
        print("✅ Enjoy & Have Fun! – Make it a great community!")
        staff_menu()
    elif staff_bar == "info":
        print("―――――――――――――")
        print("ℹ️ [!] Info")
        print("💡 This is the FACTION HUB CLI system.")
        print("📜 Version: 0.0.1")
        print("🔍 We only do other version!")
        print("⚒️ Future updates will include more features!")
        staff_menu()
    elif staff_bar == "nextUPD":
        print("―――――――――――――")
        print("[!] The next update")
        print()
        print("[*] the next update will be on the 2025-06-01")
        print("[tip] it could be before that if i want!")
        staff_menu()
    elif staff_bar == "warn_reason":
        print("―――――――――――――")
        print("⚠️ [!] Warning Reasons")
        print("🚫 Spamming – Excessive, irrelevant, or disruptive messages.")
        print("💢 Harassment – Targeting, bullying, or inappropriate behavior.")
        print("🔗 Unapproved Links – Posting harmful or unauthorized links.")
        print("❌ NSFW Content – Sharing explicit, inappropriate material.")
        print("🗣️ Disrespect – Insulting, mocking, or provoking others.")
        print("⚠️ Rule Violation – Ignoring community guidelines or mod instructions.")
        print("⛔ Hate Speech – Discrimination based on race, gender, religion, etc.")
        print("🔄 Repeated Offenses – Continuous rule-breaking despite warnings.")
        print("―――――――――――――")
        staff_menu()
    elif staff_bar == "ban_reason":
        print("―――――――――――――")
        print("⛔ [!] Ban Reasons")
        print("🚫 Severe Spamming – Continuous, excessive disruption in chat.")
        print("💢 Harassment & Threats – Engaging in targeted abuse or dangerous threats.")
        print("🔗 Malicious Links – Sharing harmful, phishing, or fraudulent links.")
        print("❌ NSFW & Inappropriate Content – Posting explicit, offensive material.")
        print("🗣️ Extreme Disrespect – Aggressive insults, racism, or personal attacks.")
        print("⚠️ Major Rule Violations – Ignoring warnings and repeated infractions.")
        print("⛔ Hate Speech – Discriminatory speech based on race, gender, or identity.")
        print("🔄 Multiple Offenses – Repeated misconduct despite prior warnings.")
        print("🚷 Ban Appeals – Case-by-case decisions by moderation team.")
        print("―――――――――――――")
        staff_menu()
    elif staff_bar == "exit":
        print()
    else:
        print("[*] Invalid cmd [*]")
        staff_menu()
def member_menu():
    cmd_bar = input("SEARCH:")
    if cmd_bar == "cmds":
        print("―――――――――――――")
        print("[*] cmds")
        print("[*] credits")
        print("[*] rules")
        print("[*] info")
        print("[*] nextUPD")
        print("[*] exit")
        print("―――――――――――――")
        member_menu()
    elif cmd_bar == "credits":
        print("―――――――――――――")
        print("[!] Credits")
        print()
        print("[*] CREATOR: alexis20114")
        member_menu()
    elif cmd_bar == "rules":
        print("―――――――――――――")
        print("📜 [!] Rules")
        print("⚠️ Respect Everyone – No bullying, discrimination, or toxic behavior.")
        print("🚫 No Spamming – Keep the chat clean and meaningful.")
        print("🛡️ Follow Admin Instructions – Mods' decisions are final.")
        print("📢 Keep It On Topic – Stay relevant to the chat or discussion.")
        print("🔞 No NSFW Content – Keep it appropriate for all members.")
        print("🔗 No Unapproved Links – Sharing harmful or unauthorized links is not allowed.")
        print("💬 Use Proper Channels – Follow the correct categories when posting.")
        print("✅ Enjoy & Have Fun! – Make it a great community!")
        member_menu()
    elif cmd_bar == "info":
        print("―――――――――――――")
        print("ℹ️ [!] Info")
        print("💡 This is the FACTION HUB CLI system.")
        print("📜 Version: 0.0.1")
        print("🔍 We only do other version!")
        print("⚒️ Future updates will include more features!")
        member_menu()
    elif cmd_bar == "nextUPD":
        print("―――――――――――――")
        print("[!] The next update")
        print()
        print("[*] the next update will be on the 2025-06-01")
        print("[tip] it could be before that if i want!")
        member_menu()
    elif cmd_bar == "exit":
        print()
    else:
        print("[*] Invalid cmd [*]")
        member_menu()
def password():
    password = input("ENTER PASSWORD:")
    if password == "password123":
        print("access granted!")
        staff_menu()
    else:
        print("access denied!")
        print("loging you as member")
        member_menu()
def starter_pack():
    print("╔═══════════════════╗")
    print("║   FACTION HUB     ║")
    print("╚═══════════════════╝")
    print("")
    print("[!] type cmds for the command")
    yesno = input("(yes)[start](no):")
    if yesno == "no":
        print("script.closed")
    elif yesno == "yes":
        yesno2 = input("[!]would you like to login as an (staff) or (member)[!]")
        if yesno2 == "staff":
            password()
        elif yesno2 == "member":
            member_menu()
        else:
            print("ERROR:0001-1")

starter_pack()